---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lxejrqae/public_html/nectoros.com/
    - mkdir -p $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - chmod 644 $DEPLOYPATH/index.html
    - chmod 644 $DEPLOYPATH/.htaccess
